v = input('Digite algo ')
print('O tipo primitivo deste valor é {}'.format(type(v)))
print('O valor só tem espaços? {}'.format(v.isspace()))
print('O valor é numérico? {}'.format(v.isnumeric()))
print('O valor é alfabético? {}'.format(v.isalpha()))
print('O valor é alfanumérico? {}'.format(v.isalnum()))
print('O valor é minúsculo? {}'.format(v.islower()))
print('O valor é MAIÚSCULO? {}'.format(v.isupper()))
print('O valor é CapItaliZado? {}'.format(v.istitle()))
